### PR TITLE
Export History, Funding, and Interest data to CSV file

### PR DESCRIPTION
**Pull request by FrescoFlacko**
### Purpose for pull request
This pull request will be adding a button to the History, Funding, and Interest tabs that will allow you to export the data to a CSV file.

### Features
* Ability to export data from History, Funding, and Interest tab into CSV
* If data is empty, will show warning message

### Translations needed
Export Data
Data exported successfully!
No data to export!

### Images
image
image

**Note: Even though the forked repo comes from Mango Heroes, this is not a Mango Heroes feature.**

### CODE REVIEW

**Comment by saml33** [comment]
Screen Shot 2021-12-03 at 10 34 09 pm

I think the tabs should be above the button in this case as it's only downloading the data from the tab.

Can we copy the style/icon position of the "Add Name" button above? Not sure this button should be larger. Can use the outline version of the icon as well.

Instead of "Export Data" in the button could be "Export CSV" or even just "Export"

**Comment by saml33** [comment]
Looking good. I think I might need to re-think the layout of the history tab but fine for now.

A couple of other things:

Is it possible to export the timestamps in local time?

Wondering if we add the Mango account name (public key if no name) to the file name as a lot of people have multiple accounts

Can we also make the file names a bit cleaner? Using deposits as an example if could be 'yyyy-mm-dd-accountName-deposits.csv'

Currently look like this for me 'Mango_Markets_-_Deposits_-_'_+_Mon_Dec_06_2021_19_28_18_GMT+1100_(Australian_Eastern_Daylight_Time).csv'

**Comment by FrescoFlacko** [comment]
> Looking good. I think I might need to re-think the layout of the history tab but fine for now.
> 
> A couple of other things:
> 
> Is it possible to export the timestamps in local time?
> 
> Wondering if we add the Mango account name (public key if no name) to the file name as a lot of people have multiple accounts
> 
> Can we also make the file names a bit cleaner? Using deposits as an example if could be 'yyyy-mm-dd-accountName-deposits.csv'
> 
> Currently look like this for me 'Mango_Markets_-_Deposits_-_'_+_Mon_Dec_06_2021_19_28_18_GMT+1100_(Australian_Eastern_Daylight_Time).csv'

Yeah I'm not liking it under the tabs but we can always revert that back if needed.

I changed the file names to have {accountName}-{tab}-{date} format. A typical user sorts their files by file name so it's better to have all exports start the same with the account name so all of their files show once sorted.

Also changed to use locale date+time string in both CSV and file name so timestamps match Mango's UI.

**Comment by saml33** [comment]
> > Looking good. I think I might need to re-think the layout of the history tab but fine for now.
> > A couple of other things:
> > Is it possible to export the timestamps in local time?
> > Wondering if we add the Mango account name (public key if no name) to the file name as a lot of people have multiple accounts
> > Can we also make the file names a bit cleaner? Using deposits as an example if could be 'yyyy-mm-dd-accountName-deposits.csv'
> > Currently look like this for me 'Mango_Markets_-_Deposits_-_'_+_Mon_Dec_06_2021_19_28_18_GMT+1100_(Australian_Eastern_Daylight_Time).csv'
> 
> Yeah I'm not liking it under the tabs but we can always revert that back if needed.
> 
> I changed the file names to have {accountName}-{tab}-{date} format. A typical user sorts their files by file name so it's better to have all exports start the same with the account name so all of their files show once sorted.
> 
> Also changed to use locale date+time string in both CSV and file name so timestamps match Mango's UI.

Cool, thanks for that. Can you add the new translation keys to the other language files? Just add them in English for now. I have a few others to get done but figure we could merge and do that later.

**Pull request merged**
