### PR TITLE
Informative onboarding

### PR DESCRIPTION
**Pull request by saml33**

### CODE REVIEW

**Comment by saml33** [comment]
Required translations:

"accept-terms": "I understand and accept the risks",
"read-more": "Read More",
"intro-feature-1": "Cross‑collateralized leverage trading",
"intro-feature-2": "All assets count as collateral to trade or borrow",
"intro-feature-3": "Deposit any asset and earn interest automatically",
"intro-feature-4": "Borrow against your assets for other DeFi activities",
"get-started": "Get Started",
"show-tips": "Show Tips",
"connect-wallet-tip-title": "Connect your wallet",
"connect-wallet-tip-desc": "We'll show you around...",
"profile-menu-tip-title": "Profile Menu",
"profile-menu-tip-desc": "Access your Mango Accounts, copy your wallet address and disconnect here.",
"themes-tip-title": "Color Themes",
"themes-tip-desc": "Mango, Dark or Light (if you're that way inclined).",
"languages-tip-title": "Multilingual?",
"languages-tip-desc": "Choose another language here. More coming soon...",
"data-refresh-tip-title": "Manual Data Refresh",
"data-refresh-tip-desc": "Data is refreshed automatically but you can manually refresh it here.",
"layout-tip-title": "Customize Layout",
"layout-tip-desc": "Unlock to re-arrange and re-size the trading panels to your liking.",
"perp-positions-tip-title": "Perp Position Details",
"perp-positions-tip-desc": "Perp positions accrue Unsettled PnL as price moves. Settling PnL adds or removes that amount from your USDC balance.",
"account-details-tip-title": "Account Details",
"account-details-tip-desc": "When you make your first deposit we'll set you up with a Mango Account. You'll need at least 0.0035 SOL in your wallet to cover the rent/cost of creating the account.",
"collateral-available-tip-title": "Collateral Available",
"collateral-available-tip-desc": "The collateral value that can be used to take on leverage. Assets carry different collateral weights depending on the risk they present to the platform.",
"account-health-tip-title": "Account Health",
"account-health-tip-desc": "To avoid liquidation you must keep your account health above 0%. To increase the health of your account, reduce borrows or deposit funds."

**Comment by tjshipe** [comment]
@saml33 this PR is still in draft state. is there anything I can help with here?

**Comment by saml33** [comment]
> @saml33 this PR is still in draft state. is there anything I can help with here?

Needs Spanish translations. Have reached out to @stevesarmiento

**Comment by tjshipe** [comment]
> > @saml33 this PR is still in draft state. is there anything I can help with here?
> 
> Needs Spanish translations. Have reached out to @stevesarmiento

I think we can merge this without the spanish translation and add it after. If I remember the ux flow, you wouldn't be able to select spanish until after the onboarding, correct?

**Comment by saml33** [comment]
> > > @saml33 this PR is still in draft state. is there anything I can help with here?
> > 
> > 
> > Needs Spanish translations. Have reached out to @stevesarmiento
> 
> I think we can merge this without the spanish translation and add it after. If I remember the ux flow, you wouldn't be able to select spanish until after the onboarding, correct?

@tjshipe No, selecting a language is now the first view

**Pull request merged**
