### PR TITLE
Adds post only slide input

### PR DESCRIPTION
**Pull request by kierangillen**
## Adds `Post & Slide` input to Trade Form

- Adds checkbox for `Post & Slide` to pass a `PerpOrderType` of type `postOnlySlide` to the form submit function.
- Issue: https://trello.com/c/8RihTYQc/106-add-post-only-slide-order-type-to-ui

- Disables price if `Post & Slide` selected:

- Tooltip: 
Screen Shot 2022-03-17 at 5 24 17 PM

- Small breakpoint:
Screen Shot 2022-03-17 at 5 44 22 PM

### CODE REVIEW

**Comment by saml33** [comment]
Looks good. We need to figure out a layout for when the trade form doesn't have much width. Having two rows introduces a scrollbar for some trade types. I'm wondering if we put POST, IOC and Post & Slide behind an expandable button "Advanced Options" or something like that. If not, using grid with 2x cols/rows should work okay.

**Comment by kierangillen** [comment]
@saml33 Could you send some screenshots with the scrollbar, I'm having trouble reproducing that issue.

**Review by tjshipe — APPROVED** [review]

**Review by tjshipe — CHANGES_REQUESTED** [review]
I have a strong preference for ternaries over `&&` in JSX. Here is some more info on the reasoning: https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx

**Comment by kierangillen** [comment]
@tjshipe Sounds good, removed the `&&`s.

**Review by tjshipe — APPROVED** [review]

**Pull request merged**
