### PR TITLE
add table date format component

### PR DESCRIPTION
**Pull request by saml33**

### CODE REVIEW

**Review by tjshipe — CHANGES_REQUESTED** [review]
We have another date display component that is pretty close to this. Is it possible to make the existing component reuseable here?

https://github.com/blockworks-foundation/mango-ui-v3/pull/190/files#diff-282283bc1ff7e741e676a6985ec4fa9e034dd76b7374f1537f2640d31f59b876

**Comment by saml33** [comment]
Yeah, I was going to remove that one to use the one here. Probably better to have the component live in TableElements?

**Comment by saml33** [comment]
Think it would likely only be used like this in a table. But then we don't have many components that export multiple components. Maybe we should start nesting components into folders like we have for some of the pages/trade form?

**Comment by tjshipe** [comment]
@saml33 the date component I linked is also used in a table. Should we delete that date component and use this one then?

**Comment by saml33** [comment]
@tjshipe yeah, have removed/replaced the existing one now. Doesn't matter much but thought the component should reference how it should be used

**Review by tjshipe — APPROVED** [review]

**Pull request merged**
