### PR TITLE
30 day interest and funding charts

### PR DESCRIPTION
**Pull request by saml33**
Adds a 30-day interest and interest value chart for each asset to the interest tab on the accounts page. Also lets users hide dust amounts of interest earned/paid.

Required translations:

"hide-dust": "Hide dust",
"interest-chart-title": "{{symbol}} Interest (Last 30 days)",
"interest-chart-value-title": "{{symbol}} Interest Value (Last 30 days)",
"net-interest-value": "Net Interest Value",
"net-interest-value-desc": "Calculated at the time it was earned/paid. This might be useful at tax time.",

@stevesarmiento

### CODE REVIEW

**Comment by rjpeterson** [comment]
Chinese translation PR submitted #77

**Comment by tjshipe** [comment]
@saml33 the charts are visible and continue to pulse when no interest has been earned. they could probably just be hidden

Screen Shot 2021-11-13 at 6 35 45 PM

**Comment by saml33** [comment]
> @saml33 the charts are visible and continue to pulse when no interest has been earned. they could probably just be hidden
> 
> Screen Shot 2021-11-13 at 6 35 45 PM

Yeah, definitely. Thought I had covered that. Will fix

**Comment by saml33** [comment]
Updated to latest @tjshipe

**Comment by tjshipe** [comment]
@saml33 I think merging in the Export functionality created new conflicts

**Pull request merged**
