### PR TITLE
Mango Heroes NFT Integration

### PR DESCRIPTION
**Pull request by FrescoFlacko**
### Purpose for pull request
This pull request will be integrating the Mango Heroes NFT collection as profile pictures in Mango Markets.

### Feature list
- Mango Heroes will be displayed as a replacement of the default avatar image
- Users can change their avatar if they have multiple avatars to choose from
- Currently selected avatar is kept in the store to be used anywhere else in the application

### How is it implemented?
We scan the connected wallet for any NFTs and then compare their update authority to the MH mint address to retrieve list of MH NFTs. The profile image will be retrieved using Metaplex code stored in `utils/metaplex` folder.

### Translations needed
- Okay
- Change Avatar
- Avatar updated successfully

### Images
image
image
image

### CODE REVIEW

**Comment by tjshipe** [comment]
@FrescoFlacko can you rebase this on the latest changes on `main` and repush?

**Comment by tjshipe** [comment]
@FrescoFlacko What is FUNDING.yml used for?

**Comment by tjshipe** [comment]
accidentally merged this before the above was addressed. reverted it for now

**Comment by FrescoFlacko** [comment]
> 

That was to add a sponsor button in the GitHub repo but that shouldn't be added in this PR. Will remove it now.

**Pull request merged**
