### PR TITLE
handle new mangogroup market in marketsinfo api

### PR DESCRIPTION
**Pull request by saml33**
Show a new mangoGroup market in the UI if it has not yet been added to the marketsInfo api.

### CODE REVIEW

**Comment by tjshipe** [comment]
@saml33 @mschneider can/should this PR be merged?

**Comment by mschneider** [comment]
Need to check with pan, he’s been overseeing the process of delisting markets from the client side

**Comment by tjshipe** [comment]
> Need to check with pan, he’s been overseeing the process of delisting markets from the client side

Does this mean you will be checking with pan?  This is a pretty small PR and it doesn't look like it has any client related changes.

**Comment by riordanp** [comment]
It's not totally necessary right now for delisting I think, since we can update the markets API before the UI without issue, but gives some protection against errors if things happen in a different order when adding/removing a market.

**Comment by mschneider** [comment]
deferred work on this for v4, trying to now waste time on it as a solution might look very different for v3

**Pull request closed without merging**
