### PR TITLE
add performance to account overview

### PR DESCRIPTION
**Pull request by saml33**

### CODE REVIEW

**Comment by tjshipe** [comment]
Screen Shot 2022-01-21 at 1 10 48 AM
 
The PNL chart colored red makes me think of a loss even though this account has positive pnl. 

I think I like the look of the Equity chart better. I'm not sure if it's because it's yellow or because it has the gradient fade at the bottom. The red PNL as it is in the screenshot feels obtrusive.

**Comment by saml33** [comment]
> Screen Shot 2022-01-21 at 1 10 48 AM
> 
> The PNL chart colored red makes me think of a loss even though this account has positive pnl.
> 
> I think I like the look of the Equity chart better, feels cleaner. I'm not sure if it's because it's yellow or because it has the gradient fade at the bottom. The red PNL as it is in the screenshot feels obtrusive.

Oh yeah, it's not supposed to be like that haha. Supposed to be green if pnl is +ve and red if -ve. I wanted to have it both green and red (if above or below 0) but there isn't an obvious way to do that with recharts.

**Comment by saml33** [comment]
@tjshipe – I'm not sure the percentage change in equity makes sense. What do you think?

**Comment by saml33** [comment]
This should hopefully be okay now @tjshipe

**Comment by tjshipe** [comment]
Screen Shot 2022-01-23 at 9 03 45 PM
Screen Shot 2022-01-23 at 9 03 32 PM

This is the same account with screenshots on the old and new version taken at the same time. I think the new version should default to showing the current account value instead of the last thing the api returns because that data can be delayed.

Also I think we should keep the label Account Value as opposed to Equity mostly for consistency and that's also the label used on ftx, dydx,

**Comment by saml33** [comment]
@tjshipe – Makes sense. Have updated

**Pull request closed without merging**
