### PR TITLE
Improve delegate modal

### PR DESCRIPTION
**Pull request by riordanp**
Update delegate modal copy, add link to docs and add clear input button

Awaiting confirmation of docs link

### CODE REVIEW

**Comment by tjshipe** [comment]
@riordanp can you fix the conflict and then will this be ready for merge?

**Comment by riordanp** [comment]
@tjshipe resolved and I'm mostly happy to deploy, I added the linked docs page on Gitbook but awaiting a review so that link will be broken un til it's published, but is the correct URL

**Comment by riordanp** [comment]
For some reason though the preview is not displaying the copy I changed but it appears locally...

**Comment by tjshipe** [comment]
Reminder to update the status of this Draft PR when you're ready for merge

**Pull request merged**
