### PR TITLE
Risk calculator v3

### PR DESCRIPTION
**Pull request by ImpossiblePairs**
The risk calculator tool has been upgraded to handle V3 spot and perps markets for the V3 health ratio calculation.

Currently the Risk Calculator doesn't consider open orders, but instead returns any quantity in orders back to the net balance. For example, if your account has 5 SOL in balance and another 5 SOL in orders, the calculator will display a 10 SOL balance. The logic here is that this allows users to use what could be available capital toward their scenario instead of trying to replicate their existing scenario. The user can then choose to simulate execution of some or all of their orders if they choose or create an entirely different scenario.

image

Quick Overview of Columns:

- Spot: Quantity of the asset in your scenario. Positive is a deposit, and negative is a borrow. Default is zero.
- Perp: Quantity of perp position for an asset. Positive is a long position and negative is a short position. Default is zero.
- Perp Entry: The entry price for the perp position. Default is current index price.
- Price: The asset price in USDC to use for scenario calculation. Default is index price.
- Value: The calculated value of your scenario spot and perp positions using the input prices.
- Liq. Price: The estimated price for the asset which would liquidate the account. This calculation assumes all other token prices remain constant.

I've tried to make the calculations as accurate as possible and test for edge cases as well as add more commenting so the code is easier to follow, please please let me know whatever there is that is missing / not working as expected and I'll fix as quickly as I'm able.

### CODE REVIEW

**Comment by tjshipe** [comment]
@ImpossiblePairs can you rebase on the latest and repush this branch to fix the conflict in useMangoStore?

**Comment by mschneider** [comment]
get errors when connecting with my basis trading account, might be using an outdated mango client?

image

**Comment by ImpossiblePairs** [comment]
@tjshipe, I rebased and did a little tidy up (main thing found was USDT scaling with the slider, which wasn't intended).

@mschneider, I'm trying to figure out what's going on with the trade history error. The client should be the latest, but as far as I can tell the issue is something to do with UsePerpPositions not being able to find the average entry price. I don't need that specific info,  but I'll see if I can figure it out anyway.

**Comment by mschneider** [comment]
Found an interesting issue:

1) edit all prices to -80%
2) set one asset to 1 USD
3) now "edit all prices" is set to 0, but prices are at a low level except
for the manually edited one
4) move the edit all prices slider to -89%, now sol is worth ~2$

It was confusing me a bit, not sure if that is expected behaviour

>

**Comment by ImpossiblePairs** [comment]
There is a feature of the calculator that might have produced what you're talking about.

The calculator is set up so that if you use the slider, then focus on or change a price, it resets the slider to 0% and keeps the modified prices (for the whole column) as the new anchor point for the slider. The reason this was done was to allow users to scroll higher percentage ranges without having to set each price when they wanted to go beyond the limits of the slider. One case this is useful in, outside of daring to dream, is for perp positions where the liquidation price of a short is outside the range of the slider. You can slide, tap the price and slide again.

Do you think that's what could have happened in your case or was it something else?

**Comment by mschneider** [comment]
yeah sounds about right, this behaviour his helpful, but very hard to discover as a feature and will probably confuse a lot of users. rather then triggering it implicitly, can you make it an explicit action>

**Comment by ImpossiblePairs** [comment]
A couple more updates made:
- Updated the anchoring of prices to be a manual button click
- Fixed NaN error when retrieving perp positions / orders if null and missing icons for new tokens added
- Added ability to include or exclude current open orders as part of their scenario

image

**Comment by ImpossiblePairs** [comment]
Small update:
- UI precision added for MSOL, BNB, and AVAX - was affecting display of the perp positions
- Short scenario summary for mobile / small screen added into the table (in the picture). Hidden when detailed summary is able to be displayed.

image

I haven't received any extra feedback, so I'm mostly assuming this has been working and is good to go.

This is probably just semantics, but one last question is if this should be called the "Health Calculator" instead of the "Risk Calculator"?

**Comment by mschneider** [comment]
conflicts remaining, but i'm all up for bringing this out to the people

**Pull request merged**
